load("//closure:defs.bzl", "closure_js_library")

package(default_visibility = ["//visibility:public"])

closure_js_library(
    name = "nodejs",
    srcs = ["nodejs.js"],
    lenient = True,
)

closure_js_library(
    name = "webworkers",
    srcs = ["webworkers.js"],
    lenient = True,
)
